name: AllInOne

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: 0 0 * * 5

jobs:
  plugin_test:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: ark version

  lint_and_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run the sh-checker
        uses: luizm/action-sh-checker@v0.1.12
        env:
          GITHUB_TOKEN: ${{ github.token }}
          #SHELLCHECK_OPTS: -e SC1004 # Optional: exclude some shellcheck warnings.
          SHFMT_OPTS: -i 2 # Optional: pass arguments to shfmt.
        with:
          sh_checker_comment: true
      - name: Install asdf
        run: |
          git clone https://github.com/asdf-vm/asdf.git $HOME/asdf

      - name: Install bats
        run: |
          sudo apt-get install bats
          bats --version

      - name: Test plugin with bats
        run: |
          . $HOME/asdf/asdf.sh
          asdf plugin-add arkade $GITHUB_WORKSPACE
          bats test
